
### Creates companies
POST  http://127.0.0.1:5000/api/companies/ HTTP/1.1
content-type: application/json

{
    "name" : "bnp"
}

### Get all companies
GET  http://127.0.0.1:5000/api/companies/ HTTP/1.1

### Get companies with id 1
GET  http://127.0.0.1:5000/api/companies/1 HTTP/1.1
###delete companies with id 1
DELETE http://127.0.0.1:5000/api/companies/3 HTTP/1.1
### update companies
PUT http://127.0.0.1:5000/api/companies/1 HTTP/1.1
content-type: application/json

{
    "name" : "credit agricole"
}
