
### Creates industry
POST  http://127.0.0.1:5000/api/industry/ HTTP/1.1
content-type: application/json

{
    "name" : "santé"
}

### Get all industry
GET  http://127.0.0.1:5000/api/industry/ HTTP/1.1

### Get industry with id 1
GET  http://127.0.0.1:5000/api/industry/1 HTTP/1.1