
### Creates applications
POST  http://127.0.0.1:5000/api/applications/ HTTP/1.1
content-type: application/json

{
    "candidate_id" : 1,
    "candidate_name" : "bob",
    "candidate_text" : "text",
    "candidate_email" : "bob@mail.com",
    "candidate_phone" : "0123456789",
    "advertisement_id" : 1,
    "state" : "sent"
}

### Get all applications
GET  http://127.0.0.1:5000/api/applications/ HTTP/1.1

### Get applications with id 1
GET  http://127.0.0.1:5000/api/applications/1 HTTP/1.1
###delete applications with id 1
DELETE http://127.0.0.1:5000/api/applications/22 HTTP/1.1
### update applications
PUT http://127.0.0.1:5000/api/applications/1 HTTP/1.1
content-type: application/json

{
    "name" : "sante"
}